#ifndef __COLORS_LEGACY_H
#define __COLORS_LEGACY_H

/* Legacy colour palette for AxxSolder.
 * The pre-refactor display had an SPI frame-size bug whose net effect on each 16-bit
 * RGB565 colour was a BYTE SWAP. The UI palette was hand-tuned against that broken
 * pipeline (colours wrapped in the old RGB_to_BRG helper). Now that the SPI is fixed
 * (colours render true), use C_*_LEGACY RAW to reproduce the original on-screen look:
 *     legacy_value = byteswap( RGB_to_BRG( original_C_* ) ) */

#define C_MAROON_LEGACY              0x0004
#define C_DARK_RED_LEGACY            0x4004
#define C_BROWN_LEGACY               0x0A2D
#define C_FIREBRICK_LEGACY           0x8825
#define C_CRIMSON_LEGACY             0xC53E
#define C_RED_LEGACY                 0xC007
#define C_TOMATO_LEGACY              0xD84F
#define C_CORAL_LEGACY               0xDF57
#define C_INDIAN_RED_LEGACY          0x575E
#define C_LIGHT_CORAL_LEGACY         0x6087
#define C_DARK_SALMON_LEGACY         0x257F
#define C_SALMON_LEGACY              0xA077
#define C_LIGHT_SALMON_LEGACY        0xE87F
#define C_ORANGE_RED_LEGACY          0xD107
#define C_DARK_ORANGE_LEGACY         0xE307
#define C_ORANGE_LEGACY              0xE907
#define C_GOLD_LEGACY                0xF507
#define C_DARK_GOLDEN_ROD_LEGACY     0xA10D
#define C_GOLDEN_ROD_LEGACY          0xE926
#define C_PALE_GOLDEN_ROD_LEGACY     0x79AF
#define C_DARK_KHAKI_LEGACY          0xED6D
#define C_KHAKI_LEGACY               0x798F
#define C_OLIVE_LEGACY               0x2004
#define C_YELLOW_LEGACY              0xFF07
#define C_YELLOW_GREEN_LEGACY        0xF334
#define C_DARK_OLIVE_GREEN_LEGACY    0x9A32
#define C_OLIVE_DRAB_LEGACY          0x6323
#define C_LAWN_GREEN_LEGACY          0xFE03
#define C_CHART_REUSE_LEGACY         0xFF03
#define C_GREEN_YELLOW_LEGACY        0x7F35
#define C_DARK_GREEN_LEGACY          0x1900
#define C_GREEN_LEGACY               0x3F00
#define C_FOREST_GREEN_LEGACY        0x2221
#define C_LIME_LEGACY                0x3F00
#define C_LIME_GREEN_LEGACY          0xB331
#define C_LIGHT_GREEN_LEGACY         0xBB94
#define C_PALE_GREEN_LEGACY          0xBE94
#define C_DARK_SEA_GREEN_LEGACY      0x6E8C
#define C_MEDIUM_SPRING_GREEN_LEGACY 0x3E98
#define C_SPRING_GREEN_LEGACY        0x3F78
#define C_SEA_GREEN_LEGACY           0xA259
#define C_MEDIUM_AQUA_MARINE_LEGACY  0x33AB
#define C_MEDIUM_SEA_GREEN_LEGACY    0xEC71
#define C_LIGHT_SEA_GREEN_LEGACY     0x2CA9
#define C_DARK_SLATE_GRAY_LEGACY     0x9451
#define C_TEAL_LEGACY                0x2080
#define C_DARK_CYAN_LEGACY           0x2288
#define C_AQUA_LEGACY                0x3FF8
#define C_CYAN_LEGACY                0x3FF8
#define C_LIGHT_CYAN_LEGACY          0xFFFE
#define C_DARK_TURQUOISE_LEGACY      0x33C8
#define C_TURQUOISE_LEGACY           0x37CA
#define C_MEDIUM_TURQUOISE_LEGACY    0x74CA
#define C_PALE_TURQUOISE_LEGACY      0x7BED
#define C_AQUA_MARINE_LEGACY         0xFFD3
#define C_POWDER_BLUE_LEGACY         0x77E5
#define C_CADET_BLUE_LEGACY          0x279B
#define C_STEEL_BLUE_LEGACY          0x60B2
#define C_CORN_FLOWER_BLUE_LEGACY    0x25EB
#define C_DEEP_SKY_BLUE_LEGACY       0x2FF8
#define C_DODGER_BLUE_LEGACY         0x24F9
#define C_LIGHT_BLUE_LEGACY          0x75E5
#define C_SKY_BLUE_LEGACY            0x33EC
#define C_LIGHT_SKY_BLUE_LEGACY      0x33F4
#define C_MIDNIGHT_BLUE_LEGACY       0xC670
#define C_NAVY_LEGACY                0x0080
#define C_DARK_BLUE_LEGACY           0x0088
#define C_MEDIUM_BLUE_LEGACY         0x00C8
#define C_BLUE_LEGACY                0x00F8
#define C_ROYAL_BLUE_LEGACY          0x1ADA
#define C_BLUE_VIOLET_LEGACY         0x4BDC
#define C_INDIGO_LEGACY              0x4082
#define C_DARK_SLATE_BLUE_LEGACY     0x4F8A
#define C_SLATE_BLUE_LEGACY          0x56CB
#define C_MEDIUM_SLATE_BLUE_LEGACY   0xDAEB
#define C_MEDIUM_PURPLE_LEGACY       0x9CDC
#define C_DARK_MAGENTA_LEGACY        0x408C
#define C_DARK_VIOLET_LEGACY         0x80D4
#define C_DARK_ORCHID_LEGACY         0xCCCC
#define C_MEDIUM_ORCHID_LEGACY       0xD5D5
#define C_PURPLE_LEGACY              0x0084
#define C_THISTLE_LEGACY             0xAFD6
#define C_PLUM_LEGACY                0xE8DE
#define C_VIOLET_LEGACY              0x60EF
#define C_MAGENTA_LEGACY             0xC0FF
#define C_ORCHID_LEGACY              0xDCD6
#define C_MEDIUM_VIOLET_RED_LEGACY   0x0586
#define C_PALE_VIOLET_RED_LEGACY     0xDC96
#define C_DEEP_PINK_LEGACY           0xC597
#define C_HOT_PINK_LEGACY            0xDAB7
#define C_LIGHT_PINK_LEGACY          0xEDBF
#define C_PINK_LEGACY                0xEFCF
#define C_ANTIQUE_WHITE_LEGACY       0xBAD7
#define C_BEIGE_LEGACY               0xBDDF
#define C_BISQUE_LEGACY              0xF8C7
#define C_BLANCHED_ALMOND_LEGACY     0xFACF
#define C_WHEAT_LEGACY               0xB7B7
#define C_CORN_SILK_LEGACY           0xFDDF
#define C_LEMON_CHIFFON_LEGACY       0xFECF
#define C_LIGHT_GOLDEN_ROD_YELLOW_LEGACY 0xBED7
#define C_LIGHT_YELLOW_LEGACY        0xFFDF
#define C_SADDLE_BROWN_LEGACY        0x5114
#define C_SIENNA_LEGACY              0xD42C
#define C_CHOCOLATE_LEGACY           0x9A26
#define C_PERU_LEGACY                0x6146
#define C_SANDY_BROWN_LEGACY         0xA967
#define C_BURLY_WOOD_LEGACY          0xED86
#define C_TAN_LEGACY                 0xAC8E
#define C_ROSY_BROWN_LEGACY          0xE38D
#define C_MOCCASIN_LEGACY            0xF8B7
#define C_NAVAJO_WHITE_LEGACY        0xF7AF
#define C_PEACH_PUFF_LEGACY          0xF6B7
#define C_MISTY_ROSE_LEGACY          0xF8DF
#define C_LAVENDER_BLUSH_LEGACY      0xFBF7
#define C_LINEN_LEGACY               0xBBE7
#define C_OLD_LACE_LEGACY            0xFDE7
#define C_PAPAYA_WHIP_LEGACY         0xFBD7
#define C_SEA_SHELL_LEGACY           0xFDEF
#define C_MINT_CREAM_LEGACY          0xBFF7
#define C_SLATE_GRAY_LEGACY          0xA093
#define C_LIGHT_SLATE_GRAY_LEGACY    0xA29B
#define C_LIGHT_STEEL_BLUE_LEGACY    0x70DD
#define C_LAVENDER_LEGACY            0x39F7
#define C_FLORAL_WHITE_LEGACY        0xFEEF
#define C_ALICE_BLUE_LEGACY          0x7DFF
#define C_GHOST_WHITE_LEGACY         0xBDFF
#define C_HONEYDEW_LEGACY            0x7FEF
#define C_IVORY_LEGACY               0xFFEF
#define C_AZURE_LEGACY               0x7FFF
#define C_SNOW_LEGACY                0xFEF7
#define C_BLACK_LEGACY               0x0000
#define C_DIM_GRAY_LEGACY            0x5A6B
#define C_GRAY_LEGACY                0x2084
#define C_DARK_GRAY_LEGACY           0x6AAD
#define C_SILVER_LEGACY              0xEFBD
#define C_LIGHT_GRAY_LEGACY          0xB4D6
#define C_GAINSBORO_LEGACY           0xF6DE
#define C_WHITE_SMOKE_LEGACY         0xBDF7
#define C_WHITE_LEGACY               0xFFFF
#define C_WHITE_39_LEGACY            0x1963
#define C_WHITE_41_LEGACY            0x5A6B
#define C_WHITE_63_LEGACY            0xE89C
#define C_WHITE_89_LEGACY            0x38E7
#define C_WHITE_94_LEGACY            0x7BEF

#endif /* __COLORS_LEGACY_H */

