M48
; DRILL file {KiCad 7.0.10} date Fri Nov  1 11:47:04 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-01T11:47:04+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0610
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.0807
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C0.0984
%
G90
G05
T1
X6.9925Y-5.6554
X7.2201Y-5.6554
T2
X6.8012Y-5.3307
T3
X6.624Y-5.3307
T5
X6.7028Y-5.3307
T6
X6.4567Y-5.7874
X6.5071Y-2.7558
X7.7071Y-2.7558
X7.7559Y-5.7874
T4
G00X6.7028Y-5.4931
M15
G01X6.7028Y-5.5226
M16
G05
M30
