#Inspired by https://github.com/jasonyang-ee/STM32-Dockerfile/tree/main
FROM docker.io/alpine:3.22.0

RUN set -eux; \
    apk add --no-cache --virtual build-dependencies \
        build-base=0.5-r3 \
        gcc=14.2.0-r6 \
        gcc-arm-none-eabi=15.1.0-r0 \
        cmake=3.31.7-r1 \
        newlib=4.5.0.20241231-r0 \
    ;

WORKDIR /app

COPY . .

RUN set -eux; \
    cmake -S . -B build; \
    cmake --build build -j$(nproc);
