#Inspired by https://github.com/jasonyang-ee/STM32-Dockerfile/tree/main
FROM docker.io/alpine:3.21.3

RUN set -eux; \
    apk add --no-cache --virtual build-dependencies \
        build-base=0.5-r3 \
        gcc=14.2.0-r4 \
        gcc-arm-none-eabi=14.2.0-r0 \
        cmake=3.31.1-r0 \
        newlib=4.4.0.20231231-r0 \
    ;

WORKDIR /app

COPY . .

RUN set -eux; \
    cmake -S . -B build; \
    cmake --build build -j$(nproc);
