#Inspired by https://github.com/jasonyang-ee/STM32-Dockerfile/tree/main
FROM docker.io/alpine:3.23.4

RUN set -eux; \
    apk add --no-cache --virtual build-dependencies \
        build-base=0.5-r3 \
        gcc=15.2.0-r2 \
        gcc-arm-none-eabi=15.2.0-r1  \
        cmake=4.1.3-r0 \
        newlib=4.5.0.20241231-r0  \
    ;

WORKDIR /app

COPY . .

RUN set -eux; \
    cmake -S . -B build; \
    cmake --build build -j$(nproc);
